/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import core.Card;
import core.Suit;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

public class App {

    private JFrame frame;

    public static void main(String[] args) throws Exception {
        App app = new App();
        app.run();
    }

    private void run() {
        SwingUtilities.invokeLater(() ->{
            frame = new JFrame("Game");
            MouseListener adapter = new MouseAdapter() {
                public void mouseClicked(MouseEvent e) {
                    Object source = e.getSource();
                    System.out.println(source);
                    if (source instanceof UICard) {
                        ((UICard) source).flip();
                        frame.repaint();
                    }
                }
            };

            frame.setSize(2000,1200);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.add(new UIMain(adapter));
            frame.setVisible(true);
        });
    }
}
