/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import core.Card;
import core.Presenter;
import core.Suit;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class App {

    private final UIController controller;
    private JFrame frame;

    public App() {
        controller = new UIController();
    }

    public void run() {
        SwingUtilities.invokeLater(() ->{
            frame = new JFrame("Game");
            controller.setFrame(frame);

            frame.setSize(1600,800);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            UIMain main = new UIMain(controller);
            frame.add(main);
            frame.setVisible(true);
            frame.addComponentListener(new ComponentAdapter() {
                public void componentResized(ComponentEvent e) {
                    Rectangle bounds = frame.getBounds();
                    int cardHeight = (int) (bounds.height * 0.2);
                    UIFactory.getInstance().setSizeFromHeight(cardHeight);
                }
            });

        });
    }

    public UIController getController() {
        return controller;
    }
}
